### PR TITLE
[APB-3591][PT]: Add Get Trust Name

### PR DESCRIPTION
**Pull request by JTY009**

### CODE REVIEW

**Comment by mariannepearson0** [comment]
update README

**Comment by sureshhmrc** [comment]
why did we add this endpoint in this service ?  i have already added it to the agent-client-authorisation and this is how its working now,

**Comment by sureshhmrc** [comment]
asking this because this is a client related info which is not a right place to add to this service

**Comment by JTY009** [comment]
Names have been coming from this service. Plus we cache so don't need to call the upstream service after the first call

**Pull request merged**
